name: CI

on:
  push:
    branches:
      - main
      - release

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore dependences
      run: npm install

    - name: Test
      run: npm run test

  publish:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Publish
      run: |        
        echo ${{ secrets.SECRET_KEY }} >> .npmrc
        npm publish --access public
