name: CI

on:
  push:
    branches: [ main ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore dependences
      run: npm install

    - name: Test
      run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - uses: actions/checkout@v4

    - name: Publish
      run: |
        npmrc=$(cat .npmrc)${{ secrets.SECRET_KEY }}
        npm publish --access public
