name: Test

on:
  push:
    branches: [ main ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore dependences
      run: yarn

    - name: Test
      run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - uses: actions/checkout@v4

    - name: Publish
      run: |
        yarn config set _authToken=${{ secrets.SECRET_KEY }}
        yarn publish --access public
